name: Deploy Super Admin

on:
  push:
    branches:
      - main

env:
  REMOTE_DIR: /var/www/storsee/backoffice
  DIST_PATH: dist/app/browser

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --force

      - run: npm run build -- --configuration production

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure Remote Directory Exists
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "mkdir -p ${{ env.REMOTE_DIR }}"

      - name: Upload Dist
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.SSH_PORT }}" \
            ${{ env.DIST_PATH }}/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.REMOTE_DIR }}/

      - name: Deployment Completed
        run: echo "✅ Super Admin deployed successfully."
